### ISSUE TITLE
uh2tk05 crear login

### ISSUE THREAD

**Issue by noahcassutti** [TSDWAD2023com1grupo1/trabajointegradorgrup1#27]

**Comment by VictoriaTSDW** [comment]
ACLARACIÓN en relación a validaciones:
- Se debe evidenciar validaciones mediante html. Ej. max, min, email,
etc.
- Se debe evidenciar como mínimo las siguientes validaciones y curso
de acción mediante javascript.
1- Login. Se debe validar un usuario y contraseña (por ahora
hardcodear en variables los datos). Si el usuario ingresa
correctamente las credenciales, se deberá navegar a la
landing page.
