### ISSUE TITLE
uh2tk03 crear registro

### ISSUE THREAD

**Issue by noahcassutti** [TSDWAD2023com1grupo1/trabajointegradorgrup1#28]

**Comment by VictoriaTSDW** [comment]
ACLARACIÓN en relación a validaciones:
- Se debe evidenciar validaciones mediante html. Ej. max, min, email,
etc.
- Se debe evidenciar como mínimo las siguientes validaciones y curso
de acción mediante javascript.

2- Registro de Usuario. Mediante javascript se debe validar
que la contraseña y el reingreso de la contraseña sean
iguales. Si la validación tanto del formulario (html) como
javascript pasa, entonces navegar a la página de login o
inicio de sesión.
